# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uploadcv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QFileDialog, QDialog, QMessageBox, QPushButton, QLabel
from PyQt5.uic import loadUi
import sys
sys.path.insert(0, './src')
import PyPDF2
import os
import requests

booking_id = 4
class UploadCV(QDialog):
    def __init__(self):
        super(UploadCV, self).__init__()
        loadUi("uploadcv.ui", self)
        self.setWindowTitle('Upload CV')
        self.uploadButton.clicked.connect(self.uploadCV)
        self.uploadedFile = None
        self.dataPaket = self.getPaketBooking(booking_id)
        self.submitBookingButton.clicked.connect(lambda: self.submitBooking(booking_id))
        self.jmlCV.setText(str(self.dataPaket.json()['jumlah_cv']) + "CV")
        self.jmlHari.setText(str(self.dataPaket.json()['durasi']) + " Hari")
        self.rincian.setText("Paket " + str(self.dataPaket.json()['jumlah_cv']) + " CV " + str(self.dataPaket.json()['durasi']) + " Hari")
        self.harga.setText("Rp" + str(self.dataPaket.json()['harga']))
        self.bookingNumber.setText("#" + str(self.dataPaket.json()['ID_Booking']))
        self.delete_button.hide()
        self.homescreen.hide()
        self.prosesReview.hide()
        self.delete_button.clicked.connect(self.deleteCV)
        self.homescreen.clicked.connect(self.goToHomeScreen)

    def uploadCV(self):
        fileName, _ = QFileDialog.getOpenFileName(self, "Upload CV File", "", "PDF Files (*.pdf)")
        if fileName:
            self.uploadedFile = fileName
            print(self.uploadedFile)
            self.fileName.setText(os.path.basename(fileName))
            self.delete_button.show()

        else:
            print("No file selected")
        
    def submitBooking(self, booking_id):
        if self.uploadedFile:
            with open(self.uploadedFile, 'rb') as f:
                files = {'uploaded_file': f}
                headers = {'Accept': 'application/json'}
                request = requests.put(f'http://127.0.0.1:8000/upload-cv?booking_id={booking_id}', files=files, headers=headers)
                print(request.status_code)
                response = request.json()
                if (response['message'] == "CV exists!"):
                    self.remove_CV_from_Booking(booking_id)
                    request = requests.put(f'http://127.0.0.1:8000/upload-cv?booking_id={booking_id}', files=files, headers=headers)
                    QMessageBox.about(self, "Success", f"CV untuk booking {booking_id} berhasil di upload!")
                else:
                    QMessageBox.about(self, "Success", f"CV untuk booking {booking_id} berhasil di upload!")
                self.delete_button.hide()
                self.homescreen.show()
                self.uploadButton.hide()
                self.submitBookingButton.hide()
                self.prosesReview.show()

        else:
            QMessageBox.warning(self, "Warning", "Please upload your CV file")
    
    def getPaketBooking(self, booking_id):
        data = requests.get(f'http://127.0.0.1:8000/paket-of-booking?booking_id={booking_id}')
        print(data.text)
        if data == None:
            return '{"ID_Booking":0,"ID_Paket":0,"jumlah_cv":0,"harga":0,"durasi":0}'
        else:
            return data
    
    def deleteCV(self):
        self.uploadedFile = None
        self.fileName.setText("No File Uploaded!")
        self.delete_button.hide()

    def remove_CV_from_Booking(self, booking_id):
        headers = {'Accept': 'application/json'}
        req = requests.put(f'http://127.0.0.1:8000/remove-cv-from-booking?booking_id={booking_id}', headers=headers)
        print(req.text)

    def goToHomeScreen(self):
        self.close()

app = QApplication(sys.argv)
window = UploadCV()
window.show()
app.exec_()